package au.org.ala.biocache.hubs

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/user/**") {
            before = {
                // Access control by convention.
                accessControl()
            }
        }

        all(uri: "/admin/**") {
            before = {
                // Access control by convention.
                accessControl()
            }
        }

        all(uri: "/buildInfo/**") {
            before = {
                // Access control by convention.
                accessControl()
            }
        }
    }
}
